/**
 * tests/03-fixtures-e2e/booking-crud.e2e.spec.ts
 * -----------------------------------------------------------------------------
 * LEVEL 3 - fixtures + end-to-end journey.
 *
 * Two things make this the "highest" level:
 *   1. The TOKEN is generated by a fixture (`bookerToken`) - no POST /auth in
 *      the spec. The `bookingApi` service object is injected too.
 *   2. It's a real CRUD journey that shares one bookingId across ordered steps:
 *
 *         create booking -> update booking -> delete booking -> verify gone
 *
 * `test.describe.serial` runs the tests in order and stops the chain if any
 * step fails (a later step is meaningless once an earlier one breaks).
 */
import { test, expect } from '../../src/fixtures/booker.fixture';
import { buildBooking } from '../../src/testdata/booking.data';

test.describe.serial('@e2e @P0 Level 3 - Booking lifecycle (token from fixture)', () => {
    // Shared across the ordered steps below.
    let bookingId: number;

    test('create a booking', async ({ bookingApi }) => {
        const payload = buildBooking({ firstname: 'E2E', lastname: 'Journey' });

        const { bookingid, booking } = await bookingApi.createBooking(payload);

        expect(bookingid).toBeGreaterThan(0);
        expect(booking.firstname).toBe('E2E');
        bookingId = bookingid;
    });

    test('update the booking (token comes from the fixture)', async ({
        bookingApi,
        bookerToken,
    }) => {
        const updated = await bookingApi.updateBooking(
            bookingId,
            buildBooking({ firstname: 'E2E', lastname: 'Updated', totalprice: 950 }),
            bookerToken,
        );

        expect(updated.lastname).toBe('Updated');
        expect(updated.totalprice).toBe(950);

        // Read it back to prove the change persisted.
        const fetched = await bookingApi.getBooking(bookingId);
        expect(fetched.lastname).toBe('Updated');
    });

    test('delete the booking and confirm it is gone', async ({ bookingApi, bookerToken }) => {
        // Booker returns 201 Created on a successful DELETE.
        const status = await bookingApi.deleteBooking(bookingId, bookerToken);
        expect(status).toBe(201);

        // The resource should now 404.
        const ghost = await bookingApi.getBookingResponse(bookingId);
        expect(ghost.status()).toBe(404);
    });
});
